name: PR Lightweight CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json
            functions-blob/package-lock.json
            
      - name: Install dependencies
        run: |
          npm ci
          cd api && npm ci
          cd ../functions-blob && npm ci
          
      - name: Lint
        run: npm run lint
        
      - name: Type check - Frontend
        run: npx tsc --noEmit
        
      - name: Type check - API
        run: cd api && npx tsc --noEmit
        
      - name: Type check - Blob Functions
        run: cd functions-blob && npx tsc --noEmit

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            api/package-lock.json
            functions-blob/package-lock.json
            
      - name: Install dependencies
        run: |
          npm ci
          cd api && npm ci
          cd ../functions-blob && npm ci
          
      - name: Test Frontend
        run: npm run test:ci
        
      - name: Test API
        run: cd api && npm test
        
      - name: Test Blob Functions
        run: cd functions-blob && npm test